### ISSUE TITLE
Error after CRUD subgenerator init

### ISSUE THREAD

**Issue by grigorovich-alex** [mujeebasif/Basic-CRUD-Joomla3#2]
events.js:182
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'replace' of undefined
    at constructor.askForProject (C:\Users\Alex\AppData\Roaming\npm\node_modules
\generator-joomla3\generators\crud\index.js:93:30)
    at C:\Users\Alex\AppData\Roaming\npm\node_modules\generator-joomla3\node_mod
ules\yeoman-generator\lib\base.js:429:16
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

**Comment by grigorovich-alex** [comment]
Can't handle this one. Any suggestions, please.

**Comment by grigorovich-alex** [comment]
Fixed by cd folder_created_by_generator and then init CRUD generator.
As you said in your Tips. :)
